import { ChoreFrequency, ChoreTimeOfDay, WeatherConditionRequirement } from './types'

export interface ChoreTemplate {
  name: string
  description: string
  points: number
  frequency: ChoreFrequency
  timeOfDay: ChoreTimeOfDay
  category: string
  icon: string
  estimatedDuration?: number
  weatherConditions?: WeatherConditionRequirement
}

export const choreTemplates: ChoreTemplate[] = [
  {
    name: 'Make Your Bed',
    description: 'Straighten sheets, arrange pillows, and smooth blankets',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'am',
    category: 'Bedroom',
    icon: '🛏️',
    estimatedDuration: 5,
  },
  {
    name: 'Clean Your Room',
    description: 'Pick up toys, organize desk, and put clothes away',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Bedroom',
    icon: '🧹',
    estimatedDuration: 20,
  },
  {
    name: 'Brush Teeth',
    description: 'Brush teeth for 2 minutes morning and night',
    points: 6,
    frequency: 'daily',
    timeOfDay: 'both',
    category: 'Personal Hygiene',
    icon: '🪥',
    estimatedDuration: 3,
  },
  {
    name: 'Brush Teeth (Morning)',
    description: 'Brush teeth for 2 minutes after breakfast',
    points: 3,
    frequency: 'daily',
    timeOfDay: 'am',
    category: 'Personal Hygiene',
    icon: '🪥',
    estimatedDuration: 3,
  },
  {
    name: 'Brush Teeth (Night)',
    description: 'Brush teeth for 2 minutes before bed',
    points: 3,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Personal Hygiene',
    icon: '🦷',
    estimatedDuration: 3,
  },
  {
    name: 'Set the Table',
    description: 'Place plates, utensils, and napkins for dinner',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Kitchen',
    icon: '🍽️',
    estimatedDuration: 5,
  },
  {
    name: 'Clear the Table',
    description: 'Remove dishes and wipe down table after meals',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Kitchen',
    icon: '✨',
    estimatedDuration: 10,
  },
  {
    name: 'Load Dishwasher',
    description: 'Rinse and load dirty dishes into the dishwasher',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Kitchen',
    icon: '🫧',
    estimatedDuration: 10,
  },
  {
    name: 'Unload Dishwasher',
    description: 'Put clean dishes away in the correct places',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'am',
    category: 'Kitchen',
    icon: '📦',
    estimatedDuration: 10,
  },
  {
    name: 'Wash Dishes',
    description: 'Hand wash dishes, pots, and pans',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Kitchen',
    icon: '🧽',
    estimatedDuration: 15,
  },
  {
    name: 'Take Out Trash',
    description: 'Empty trash cans and replace with new bags',
    points: 8,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Cleaning',
    icon: '🗑️',
    estimatedDuration: 5,
  },
  {
    name: 'Take Out Recycling',
    description: 'Sort and take recycling to bins',
    points: 8,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '♻️',
    estimatedDuration: 10,
  },
  {
    name: 'Vacuum Living Room',
    description: 'Vacuum all carpets and rugs in the living room',
    points: 20,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '🧹',
    estimatedDuration: 20,
  },
  {
    name: 'Sweep Kitchen Floor',
    description: 'Sweep entire kitchen floor and behind appliances',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Cleaning',
    icon: '🧹',
    estimatedDuration: 10,
  },
  {
    name: 'Mop Floors',
    description: 'Mop kitchen and bathroom floors',
    points: 20,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '🪣',
    estimatedDuration: 30,
  },
  {
    name: 'Dust Furniture',
    description: 'Dust all surfaces in living areas',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '🧹',
    estimatedDuration: 15,
  },
  {
    name: 'Clean Bathroom',
    description: 'Wipe counters, clean toilet, and organize',
    points: 25,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Bathroom',
    icon: '🚿',
    estimatedDuration: 25,
  },
  {
    name: 'Clean Mirrors',
    description: 'Clean all mirrors and glass surfaces',
    points: 10,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Bathroom',
    icon: '🪞',
    estimatedDuration: 10,
  },
  {
    name: 'Fold Laundry',
    description: 'Fold clean laundry and put in drawers',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Laundry',
    icon: '👕',
    estimatedDuration: 20,
  },
  {
    name: 'Sort Laundry',
    description: 'Separate clothes by color and fabric type',
    points: 8,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Laundry',
    icon: '🧺',
    estimatedDuration: 10,
  },
  {
    name: 'Put Away Laundry',
    description: 'Put folded clothes in correct drawers and closets',
    points: 10,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Laundry',
    icon: '👔',
    estimatedDuration: 10,
  },
  {
    name: 'Feed Pets',
    description: 'Fill pet food and water bowls',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'both',
    category: 'Pet Care',
    icon: '🐕',
    estimatedDuration: 5,
  },
  {
    name: 'Walk the Dog',
    description: 'Take dog for 15-minute walk',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Pet Care',
    icon: '🦮',
    estimatedDuration: 20,
  },
  {
    name: 'Clean Litter Box',
    description: 'Scoop and clean cat litter box',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Pet Care',
    icon: '🐱',
    estimatedDuration: 5,
  },
  {
    name: 'Water Plants',
    description: 'Water all indoor and outdoor plants',
    points: 8,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Outdoor',
    icon: '🪴',
    estimatedDuration: 10,
    weatherConditions: {
      conditions: ['clear', 'cloudy'],
    },
  },
  {
    name: 'Rake Leaves',
    description: 'Rake leaves in yard and bag them',
    points: 25,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Outdoor',
    icon: '🍂',
    estimatedDuration: 45,
    weatherConditions: {
      conditions: ['clear', 'cloudy'],
    },
  },
  {
    name: 'Mow Lawn',
    description: 'Mow grass in front and back yard',
    points: 30,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Outdoor',
    icon: '🌱',
    estimatedDuration: 60,
    weatherConditions: {
      conditions: ['clear', 'cloudy'],
    },
  },
  {
    name: 'Pull Weeds',
    description: 'Remove weeds from garden and flower beds',
    points: 20,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Outdoor',
    icon: '🌿',
    estimatedDuration: 30,
    weatherConditions: {
      conditions: ['clear', 'cloudy'],
    },
  },
  {
    name: 'Organize Toys',
    description: 'Sort and put away all toys in proper places',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Bedroom',
    icon: '🧸',
    estimatedDuration: 15,
  },
  {
    name: 'Organize Backpack',
    description: 'Empty, organize, and repack school backpack',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'School',
    icon: '🎒',
    estimatedDuration: 5,
  },
  {
    name: 'Complete Homework',
    description: 'Finish all homework assignments before bedtime',
    points: 20,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'School',
    icon: '📚',
    estimatedDuration: 45,
  },
  {
    name: 'Practice Instrument',
    description: 'Practice musical instrument for 20 minutes',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Activities',
    icon: '🎵',
    estimatedDuration: 20,
  },
  {
    name: 'Read for 20 Minutes',
    description: 'Read a book for at least 20 minutes',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Activities',
    icon: '📖',
    estimatedDuration: 20,
  },
  {
    name: 'Help with Groceries',
    description: 'Help carry and put away groceries',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Errands',
    icon: '🛒',
    estimatedDuration: 15,
  },
  {
    name: 'Wash the Car',
    description: 'Wash and dry family car inside and out',
    points: 30,
    frequency: 'bi-weekly',
    timeOfDay: 'anytime',
    category: 'Outdoor',
    icon: '🚗',
    estimatedDuration: 45,
    weatherConditions: {
      conditions: ['clear'],
      minTemp: 50,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Clean Windows',
    description: 'Clean all windows inside and outside',
    points: 25,
    frequency: 'bi-weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '🪟',
    estimatedDuration: 30,
  },
  {
    name: 'Organize Garage',
    description: 'Tidy and organize garage or storage area',
    points: 35,
    frequency: 'bi-weekly',
    timeOfDay: 'anytime',
    category: 'Organizing',
    icon: '🏠',
    estimatedDuration: 60,
  },
  {
    name: 'Change Bed Sheets',
    description: 'Remove old sheets and put on fresh clean sheets',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Bedroom',
    icon: '🛏️',
    estimatedDuration: 15,
  },
  {
    name: 'Empty Bathroom Trash',
    description: 'Empty trash and replace liner in bathroom',
    points: 5,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Bathroom',
    icon: '🗑️',
    estimatedDuration: 3,
  },
  {
    name: 'Wipe Door Handles',
    description: 'Disinfect all door handles and light switches',
    points: 10,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Cleaning',
    icon: '🚪',
    estimatedDuration: 10,
  },
  {
    name: 'Sort Mail',
    description: 'Organize incoming mail and recycle junk mail',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'pm',
    category: 'Organizing',
    icon: '📬',
    estimatedDuration: 5,
  },
  {
    name: 'Set Up for Breakfast',
    description: 'Set table with bowls, spoons, and breakfast items',
    points: 5,
    frequency: 'daily',
    timeOfDay: 'am',
    category: 'Kitchen',
    icon: '🥣',
    estimatedDuration: 5,
  },
  // Weather-based chores
  {
    name: 'Shovel Snow',
    description: 'Shovel snow from driveway and walkway',
    points: 40,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '⛄',
    estimatedDuration: 60,
    weatherConditions: {
      conditions: ['snowy'],
    },
  },
  {
    name: 'Salt Driveway',
    description: 'Spread salt or ice melt on driveway and walkway',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🧂',
    estimatedDuration: 15,
    weatherConditions: {
      conditions: ['snowy', 'cold'],
      maxTemp: 32,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Bring in Outdoor Furniture',
    description: 'Bring outdoor furniture inside or cover it',
    points: 20,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🪑',
    estimatedDuration: 25,
    weatherConditions: {
      conditions: ['rainy', 'snowy'],
    },
  },
  {
    name: 'Set Up Sprinkler',
    description: 'Set up and run the lawn sprinkler',
    points: 10,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '💧',
    estimatedDuration: 15,
    weatherConditions: {
      conditions: ['clear'],
      minTemp: 60,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Clean Outdoor Windows',
    description: 'Wash the outside of windows',
    points: 20,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🪟',
    estimatedDuration: 30,
    weatherConditions: {
      conditions: ['clear', 'cloudy'],
      minTemp: 50,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Fill Bird Feeders',
    description: 'Refill outdoor bird feeders',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🐦',
    estimatedDuration: 10,
    weatherConditions: {
      conditions: ['any'],
    },
  },
  {
    name: 'Walk the Dog (Weather)',
    description: 'Take the dog for a walk in pleasant weather',
    points: 15,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🐕',
    estimatedDuration: 20,
    weatherConditions: {
      conditions: ['clear', 'cloudy', 'mild'],
      minTemp: 40,
      maxTemp: 85,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Play Outside',
    description: 'Spend time playing outdoors',
    points: 10,
    frequency: 'daily',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '⚽',
    estimatedDuration: 30,
    weatherConditions: {
      conditions: ['clear', 'mild'],
      minTemp: 50,
      maxTemp: 85,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Put Away Winter Gear',
    description: 'Organize and put away coats, boots, and winter items',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🧥',
    estimatedDuration: 20,
    weatherConditions: {
      conditions: ['hot', 'mild'],
      minTemp: 60,
      unit: 'fahrenheit',
    },
  },
  {
    name: 'Organize Cold Weather Clothes',
    description: 'Sort and organize winter clothing',
    points: 15,
    frequency: 'weekly',
    timeOfDay: 'anytime',
    category: 'Weather',
    icon: '🧤',
    estimatedDuration: 20,
    weatherConditions: {
      conditions: ['cold', 'snowy'],
      maxTemp: 40,
      unit: 'fahrenheit',
    },
  },
]

export const choreCategories = [
  'All',
  'Bedroom',
  'Kitchen',
  'Bathroom',
  'Cleaning',
  'Laundry',
  'Pet Care',
  'Outdoor',
  'Weather',
  'School',
  'Activities',
  'Errands',
  'Organizing',
  'Personal Hygiene',
]

export function getTemplatesByCategory(category: string): ChoreTemplate[] {
  if (category === 'All') {
    return choreTemplates
  }
  return choreTemplates.filter((template) => template.category === category)
}
