import { ChoreFrequency } from './types'

export interface ChoreTemplate {
  name: string
  description: string
  points: number
  frequency: ChoreFrequency
  category: string
  icon: string
}

export const choreTemplates: ChoreTemplate[] = [
  {
    name: 'Make Your Bed',
    description: 'Straighten sheets, arrange pillows, and smooth blankets',
    points: 5,
    frequency: 'daily',
    category: 'Bedroom',
    icon: '🛏️',
  },
  {
    name: 'Clean Your Room',
    description: 'Pick up toys, organize desk, and put clothes away',
    points: 15,
    frequency: 'daily',
    category: 'Bedroom',
    icon: '🧹',
  },
  {
    name: 'Brush Teeth (Morning)',
    description: 'Brush teeth for 2 minutes after breakfast',
    points: 3,
    frequency: 'daily',
    category: 'Personal Hygiene',
    icon: '🪥',
  },
  {
    name: 'Brush Teeth (Night)',
    description: 'Brush teeth for 2 minutes before bed',
    points: 3,
    frequency: 'daily',
    category: 'Personal Hygiene',
    icon: '🦷',
  },
  {
    name: 'Set the Table',
    description: 'Place plates, utensils, and napkins for dinner',
    points: 5,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '🍽️',
  },
  {
    name: 'Clear the Table',
    description: 'Remove dishes and wipe down table after meals',
    points: 5,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '✨',
  },
  {
    name: 'Load Dishwasher',
    description: 'Rinse and load dirty dishes into the dishwasher',
    points: 10,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '🫧',
  },
  {
    name: 'Unload Dishwasher',
    description: 'Put clean dishes away in the correct places',
    points: 10,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '📦',
  },
  {
    name: 'Wash Dishes',
    description: 'Hand wash dishes, pots, and pans',
    points: 15,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '🧽',
  },
  {
    name: 'Take Out Trash',
    description: 'Empty trash cans and replace with new bags',
    points: 8,
    frequency: 'daily',
    category: 'Cleaning',
    icon: '🗑️',
  },
  {
    name: 'Take Out Recycling',
    description: 'Sort and take recycling to bins',
    points: 8,
    frequency: 'weekly',
    category: 'Cleaning',
    icon: '♻️',
  },
  {
    name: 'Vacuum Living Room',
    description: 'Vacuum all carpets and rugs in the living room',
    points: 20,
    frequency: 'weekly',
    category: 'Cleaning',
    icon: '🧹',
  },
  {
    name: 'Sweep Kitchen Floor',
    description: 'Sweep entire kitchen floor and behind appliances',
    points: 10,
    frequency: 'daily',
    category: 'Cleaning',
    icon: '🧹',
  },
  {
    name: 'Mop Floors',
    description: 'Mop kitchen and bathroom floors',
    points: 20,
    frequency: 'weekly',
    category: 'Cleaning',
    icon: '🪣',
  },
  {
    name: 'Dust Furniture',
    description: 'Dust all surfaces in living areas',
    points: 15,
    frequency: 'weekly',
    category: 'Cleaning',
    icon: '🧹',
  },
  {
    name: 'Clean Bathroom',
    description: 'Wipe counters, clean toilet, and organize',
    points: 25,
    frequency: 'weekly',
    category: 'Bathroom',
    icon: '🚿',
  },
  {
    name: 'Clean Mirrors',
    description: 'Clean all mirrors and glass surfaces',
    points: 10,
    frequency: 'weekly',
    category: 'Bathroom',
    icon: '🪞',
  },
  {
    name: 'Fold Laundry',
    description: 'Fold clean laundry and put in drawers',
    points: 15,
    frequency: 'weekly',
    category: 'Laundry',
    icon: '👕',
  },
  {
    name: 'Sort Laundry',
    description: 'Separate clothes by color and fabric type',
    points: 8,
    frequency: 'weekly',
    category: 'Laundry',
    icon: '🧺',
  },
  {
    name: 'Put Away Laundry',
    description: 'Put folded clothes in correct drawers and closets',
    points: 10,
    frequency: 'weekly',
    category: 'Laundry',
    icon: '👔',
  },
  {
    name: 'Feed Pets',
    description: 'Fill pet food and water bowls',
    points: 5,
    frequency: 'daily',
    category: 'Pet Care',
    icon: '🐕',
  },
  {
    name: 'Walk the Dog',
    description: 'Take dog for 15-minute walk',
    points: 15,
    frequency: 'daily',
    category: 'Pet Care',
    icon: '🦮',
  },
  {
    name: 'Clean Litter Box',
    description: 'Scoop and clean cat litter box',
    points: 10,
    frequency: 'daily',
    category: 'Pet Care',
    icon: '🐱',
  },
  {
    name: 'Water Plants',
    description: 'Water all indoor and outdoor plants',
    points: 8,
    frequency: 'weekly',
    category: 'Outdoor',
    icon: '🪴',
  },
  {
    name: 'Rake Leaves',
    description: 'Rake leaves in yard and bag them',
    points: 25,
    frequency: 'weekly',
    category: 'Outdoor',
    icon: '🍂',
  },
  {
    name: 'Mow Lawn',
    description: 'Mow grass in front and back yard',
    points: 30,
    frequency: 'weekly',
    category: 'Outdoor',
    icon: '🌱',
  },
  {
    name: 'Pull Weeds',
    description: 'Remove weeds from garden and flower beds',
    points: 20,
    frequency: 'weekly',
    category: 'Outdoor',
    icon: '🌿',
  },
  {
    name: 'Organize Toys',
    description: 'Sort and put away all toys in proper places',
    points: 10,
    frequency: 'daily',
    category: 'Bedroom',
    icon: '🧸',
  },
  {
    name: 'Organize Backpack',
    description: 'Empty, organize, and repack school backpack',
    points: 5,
    frequency: 'daily',
    category: 'School',
    icon: '🎒',
  },
  {
    name: 'Complete Homework',
    description: 'Finish all homework assignments before bedtime',
    points: 20,
    frequency: 'daily',
    category: 'School',
    icon: '📚',
  },
  {
    name: 'Practice Instrument',
    description: 'Practice musical instrument for 20 minutes',
    points: 15,
    frequency: 'daily',
    category: 'Activities',
    icon: '🎵',
  },
  {
    name: 'Read for 20 Minutes',
    description: 'Read a book for at least 20 minutes',
    points: 10,
    frequency: 'daily',
    category: 'Activities',
    icon: '📖',
  },
  {
    name: 'Help with Groceries',
    description: 'Help carry and put away groceries',
    points: 15,
    frequency: 'weekly',
    category: 'Errands',
    icon: '🛒',
  },
  {
    name: 'Wash the Car',
    description: 'Wash and dry family car inside and out',
    points: 30,
    frequency: 'bi-weekly',
    category: 'Outdoor',
    icon: '🚗',
  },
  {
    name: 'Clean Windows',
    description: 'Clean all windows inside and outside',
    points: 25,
    frequency: 'bi-weekly',
    category: 'Cleaning',
    icon: '🪟',
  },
  {
    name: 'Organize Garage',
    description: 'Tidy and organize garage or storage area',
    points: 35,
    frequency: 'bi-weekly',
    category: 'Organizing',
    icon: '🏠',
  },
  {
    name: 'Change Bed Sheets',
    description: 'Remove old sheets and put on fresh clean sheets',
    points: 15,
    frequency: 'weekly',
    category: 'Bedroom',
    icon: '🛏️',
  },
  {
    name: 'Empty Bathroom Trash',
    description: 'Empty trash and replace liner in bathroom',
    points: 5,
    frequency: 'weekly',
    category: 'Bathroom',
    icon: '🗑️',
  },
  {
    name: 'Wipe Door Handles',
    description: 'Disinfect all door handles and light switches',
    points: 10,
    frequency: 'weekly',
    category: 'Cleaning',
    icon: '🚪',
  },
  {
    name: 'Sort Mail',
    description: 'Organize incoming mail and recycle junk mail',
    points: 5,
    frequency: 'daily',
    category: 'Organizing',
    icon: '📬',
  },
  {
    name: 'Set Up for Breakfast',
    description: 'Set table with bowls, spoons, and breakfast items',
    points: 5,
    frequency: 'daily',
    category: 'Kitchen',
    icon: '🥣',
  },
]

export const choreCategories = [
  'All',
  'Bedroom',
  'Kitchen',
  'Bathroom',
  'Cleaning',
  'Laundry',
  'Pet Care',
  'Outdoor',
  'School',
  'Activities',
  'Errands',
  'Organizing',
  'Personal Hygiene',
]

export function getTemplatesByCategory(category: string): ChoreTemplate[] {
  if (category === 'All') {
    return choreTemplates
  }
  return choreTemplates.filter((template) => template.category === category)
}
